"""empty message

Revision ID: 043d78c0b734
Revises: 12e3318053f1
Create Date: 2016-08-04 17:26:40.709000

"""

# revision identifiers, used by Alembic.
revision = '043d78c0b734'
down_revision = '12e3318053f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BizEmail', sa.String(length=100), nullable=True),
    sa.Column('BizName', sa.String(length=180), nullable=True),
    sa.Column('Password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_BizEmail'), 'users', ['BizEmail'], unique=True)
    op.create_index(op.f('ix_users_BizName'), 'users', ['BizName'], unique=False)
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('BizEmail', sa.VARCHAR(length=100), nullable=True),
    sa.Column('BizName', sa.VARCHAR(length=180), nullable=True),
    sa.Column('Password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_users_BizName'), table_name='users')
    op.drop_index(op.f('ix_users_BizEmail'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    ### end Alembic commands ###
