"""empty message

Revision ID: 12e3318053f1
Revises: None
Create Date: 2016-06-03 14:33:09.959000

"""

# revision identifiers, used by Alembic.
revision = '12e3318053f1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biz_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BizEmail', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_emails_BizEmail'), 'biz_emails', ['BizEmail'], unique=True)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=120), nullable=False),
    sa.Column('Comments', sa.String(length=1800), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_Title'), 'requests', ['Title'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BizEmail', sa.String(length=100), nullable=True),
    sa.Column('BizName', sa.String(length=180), nullable=True),
    sa.Column('Password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_BizEmail'), 'user', ['BizEmail'], unique=True)
    op.create_index(op.f('ix_user_BizName'), 'user', ['BizName'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_BizName'), table_name='user')
    op.drop_index(op.f('ix_user_BizEmail'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_requests_Title'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_biz_emails_BizEmail'), table_name='biz_emails')
    op.drop_table('biz_emails')
    ### end Alembic commands ###
